// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/kshvyryaev/cyber-meower-meower-service/pkg"
	"github.com/kshvyryaev/cyber-meower-meower-service/pkg/controller/grpc"
	"github.com/kshvyryaev/cyber-meower-meower-service/pkg/controller/http"
	"github.com/kshvyryaev/cyber-meower-meower-service/pkg/controller/http/middleware"
	"github.com/kshvyryaev/cyber-meower-meower-service/pkg/event"
	"github.com/kshvyryaev/cyber-meower-meower-service/pkg/repository"
	"github.com/kshvyryaev/cyber-meower-meower-service/pkg/service"
	"github.com/kshvyryaev/cyber-meower-meower-service/pkg/usecase"
)

// Injectors from wire.go:

func InitializeHttpServer() (*http.HttpServer, func(), error) {
	config := pkg.ProvideConfig()
	meowTranslatorService := service.ProvideMeowTranslatorService()
	logger, cleanup, err := pkg.ProvideZap()
	if err != nil {
		return nil, nil, err
	}
	db, cleanup2, err := repository.ProvidePostgres(config, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	postgresMeowRepository := repository.ProvidePostgresMeowRepository(db)
	encodedConn, cleanup3, err := event.ProvideNats(config)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	natsMeowEventPublisher, cleanup4, err := event.ProvideNatsMeowEventPublisher(encodedConn)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	meowUsecase := usecase.ProvideMeowUsecase(meowTranslatorService, postgresMeowRepository, natsMeowEventPublisher)
	httpMeowController := http.ProvideHttpMeowController(meowUsecase)
	httpErrorHandlerMiddleware := middleware.ProvideHttpErrorHandlerMiddleware(logger)
	httpRecoveryHandlerMiddleware := middleware.ProvideHttpRecoveryHandlerMiddleware(logger)
	httpServer := http.ProvideHttpServer(config, httpMeowController, httpErrorHandlerMiddleware, httpRecoveryHandlerMiddleware)
	return httpServer, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

func InitializeGrpcServer() (*grpc.GrpcServer, func(), error) {
	config := pkg.ProvideConfig()
	meowTranslatorService := service.ProvideMeowTranslatorService()
	logger, cleanup, err := pkg.ProvideZap()
	if err != nil {
		return nil, nil, err
	}
	db, cleanup2, err := repository.ProvidePostgres(config, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	postgresMeowRepository := repository.ProvidePostgresMeowRepository(db)
	encodedConn, cleanup3, err := event.ProvideNats(config)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	natsMeowEventPublisher, cleanup4, err := event.ProvideNatsMeowEventPublisher(encodedConn)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	meowUsecase := usecase.ProvideMeowUsecase(meowTranslatorService, postgresMeowRepository, natsMeowEventPublisher)
	grpcMeowController := grpc.ProvideGrpcMeowController(meowUsecase)
	grpcErrorHandlerInterceptor := grpc.ProvideGrpcErrorHandlerInterceptor(logger)
	grpcServer := grpc.ProvideGrpcServer(config, grpcMeowController, grpcErrorHandlerInterceptor)
	return grpcServer, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
