// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/kshvyryaev/cyber-meower-meower-service/pkg/command"
	"github.com/kshvyryaev/cyber-meower-meower-service/pkg/config"
	"github.com/kshvyryaev/cyber-meower-meower-service/pkg/controller/http"
	"github.com/kshvyryaev/cyber-meower-meower-service/pkg/event"
	"github.com/kshvyryaev/cyber-meower-meower-service/pkg/repository"
	"github.com/kshvyryaev/cyber-meower-meower-service/pkg/service"
	"go.uber.org/zap"
)

// Injectors from wire.go:

func InitializeHttpServer(logger *zap.Logger) (*controller.HttpServer, func(), error) {
	configConfig := config.ProvideConfig()
	meowTranslatorService := service.ProvideMeowTranslatorService()
	postgresConnection, cleanup, err := repository.ProvidePostgresConnection(configConfig, logger)
	if err != nil {
		return nil, nil, err
	}
	postgresMeowRepository := repository.ProvidePostgresMeowRepository(postgresConnection)
	natsEventPublisher, cleanup2, err := event.ProvideNatsEventPublisher(configConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	сreateMeowCommandHandler := command.ProvideСreateMeowCommandHandler(meowTranslatorService, postgresMeowRepository, natsEventPublisher)
	meowController := controller.ProvideMeowController(сreateMeowCommandHandler)
	errorHandlerMiddleware := controller.ProvideErrorHandlerMiddleware(logger)
	recoveryHandlerMiddleware := controller.ProvideRecoveryHandlerMiddleware(logger)
	httpServer := controller.ProvideHttpServer(configConfig, meowController, errorHandlerMiddleware, recoveryHandlerMiddleware)
	return httpServer, func() {
		cleanup2()
		cleanup()
	}, nil
}
