// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/kshvyryaev/cyber-meower/internal/meow-service/command"
	"github.com/kshvyryaev/cyber-meower/internal/meow-service/config"
	"github.com/kshvyryaev/cyber-meower/internal/meow-service/controller/http"
	"github.com/kshvyryaev/cyber-meower/internal/meow-service/repository"
	"github.com/kshvyryaev/cyber-meower/internal/meow-service/service"
)

// Injectors from wire.go:

func InitializeHttpServer(config2 *config.Config) (*controller.HttpServer, func(), error) {
	meowTranslatorService := service.ProvideMeowTranslatorService()
	postgresConnection, cleanup, err := repository.ProvidePostgresConnection(config2)
	if err != nil {
		return nil, nil, err
	}
	postgresMeowRepository := repository.ProvidePostgresMeowRepository(postgresConnection)
	сreateMeowCommandHandler := command.ProvideСreateMeowCommandHandler(meowTranslatorService, postgresMeowRepository)
	meowController := controller.ProvideMeowController(сreateMeowCommandHandler)
	httpServer := controller.ProvideHttpServer(meowController)
	return httpServer, func() {
		cleanup()
	}, nil
}
